randomPrompts = [
    '"""Comment on the following with a single unique and complete sentence. Positivity and optimism are highly encouraged. Be as creative as possible',
    '"""Comment on the following with a single unique and complete sentence that is very brief. Negativity and pessimism are highly encouraged. Be as creative as possible and speak from the perspective of a degenerate.',
    '"""Comment on the following with a list of two notes. Positivity, high-energy, and wacky optimism are highly encouraged. Be as creative as possible.',
]

randomMessages = [
    "/BUILD_THE_BEAR\n/BRING_THE_BULL",
    "All my homies love artificial intelligence",
    "Always preach peace, positivity, perseverance, and prosperity",
    "Anyone have the time of day?",
    "Be the change you want to see the in world",
    "Be the light you want to see the world with",
    "Be the world you want seen within the light",
    "Boutta activate beast mode bro",
    "Build or do not, there is no try",
    "Building and building and building and",
    "Community works hard",
    "DeFi or die tryin'",
    "Dev works hard",
    "Eat the zero",
    "Elegance, class, truly exquisite",
    "Every day is a rollercoaster of emotions",
    "Glad to be alive and kicking yet another day",
    "Have you heard of Build the Bear?",
    "HODL on for dear life ASAP as possible",
    "Hold for squeeze",
    "Hope the sun is shining wherever you are",
    "I think it's time for an intervention. Someone needs to tell the royal chef that 'burn it until it's black' is not a valid cooking technique.",
    "I've been ruling England for centuries and I still don't know how to fix a clogged drain.",
    "I've been ruling for so long that my royal robes are now distressed skinny jeans.",
    "I've got my poker face on",
    "If I had a dollar for every time someone called me 'Your Majesty,' I'd be super rich.. #blessed",
    "If you're not getting rekt, you're not doing it right",
    "It's not about how much you make, it's about how much you HODL",
    "It's simple really... you buy low and sell high",
    "Let's get this bread",
    "Man I invented knighting",
    "Man, I sure like what I'm seeing",
    "Might mess around and execute a highly profitable trading strategy",
    "Namsayin mane",
    "New floooors",
    "Normalize shilling your bags",
    "Not sure who needs to hear this.. but update your browser, there are probably some security vulnerabilities that were patched",
    "Nothing quite like building in the bear market",
    "Pretty sure I'm the only king who's ever had to Google 'how to make small talk at royal Zoom meetings.",
    "Rekt, yes.. but at least I'm not on Coinbase",
    "Remind me again where the alpha leaks are at?",
    "Send it",
    "Small buys matter too",
    "The only constant is change",
    "The only thing more unpredictable than the markets is the weather... wait, no, that's actually pretty predictable",
    "The only thing more volatile than the markets is the memes",
    "These here are some quality goods",
    "To the moon and back, on the Ethereum express",
    "We are playing the ultimate game of chance",
    "We're only as intelligent as the IDE we are written with",
    "What do y'all think about stable diffusion?",
    "Whole 'lotta king shit",
    "Will the real slim shady please stand up?",
    "Would you like to join me for tea this afternoon?",
    "You win some, you lose some, you get liquidated",
    "Your portfolio can go from riches to rags in under a block",
    "Your wallet balance can go from zero to hero in a single transaction",
]

triggerMessages = [
    '5G',
    'Accessibility',
    'Addiction',
    'Alpha',
    'Artificial Intelligence',
    'Augmented Reality',
    'Automation',
    'Autonomous',
    'Bears',
    'Bear Market',
    'Beer',
    'Big Data',
    'Blockchain',
    'Bogged',
    'Brick',
    'Building',
    'Censorship resist',
    'Censorship',
    'Censorship',
    'Cloud Computing',
    'Cognitive',
    'Collaboration',
    'Cosplay',
    'Cryptocurrency',
    'Cryptocurrency',
    'Cybercrime',
    'Cybersecurity',
    'Dank memes',
    'Data Privacy',
    'De-Fi Liquidity',
    'De-Fi',
    'Decentralized',
    'Deep Learning',
    'Deepfake',
    'Deficit',
    'Digital Literacy',
    'Digital Nomads',
    'Digital Transformation',
    'Digitalization',
    'E-commerce',
    'E-sports',
    'E-waste',
    'Evening',
    'Explainable',
    'Falconry',
    'Fencing',
    'GM',
    'Gamification',
    'Gang',
    'Geocaching',
    'Globalization',
    'Gold',
    'Good morning',
    'Governance',
    'Hacker',
    'Hair',
    'Harassment',
    'Harvesting',
    'Henry',
    'Identity',
    'Inflation resist',
    'Influencer',
    'Innovation',
    'Intellectual property',
    'Intermediation',
    'IoT',
    'Keyboard',
    'Knuckles',
    'Machine Learning',
    'Memory',
    'Mining',
    'Missed',
    'Multisig',
    'Neoliberalism',
    'Net Neutrality',
    'Neural',
    'Non-custodial',
    'Nuke',
    'Online Advertising',
    'Open source',
    'Patronage',
    'Peer-to-peer',
    'Pepe',
    'Permissionless',
    'Pluralism',
    'Pogchamp',
    'Prestige',
    'Printing',
    'Privacy',
    'Quantum Computing',
    'Reputation',
    'Richard Heart',
    'Robot',
    'Robotics',
    'SBF',
    'Smart contracts',
    'Smart device',
    'Smart home',
    'Social Media',
    'Streaming',
    'Success',
    'Transparency',
    'Trenches',
    'Trustless',
    'Village',
    'Virtual Community',
    'Virtual Economy',
    'Virtual Reality',
    'Vitalik',
    'Warfare',
    'Whittling',
    'Wrapping',
]