ahenryCommands = {
    "/start": "Simply add me as an admin in your chat",
    "/about": "Henry the Hypemachine is an open-source project brought to you by *Build the Bear*! Simply add him as an admin in your chat to get started.\n\nIf you'd to contribute or take a peek under the hood, check him out on GitHub: github.com/buildingthebear/henry\n\n*Keep up with us - @buildingthebear on most platforms or at www.buildthebear.market*",
    "/marketing": "Please DM me with your marketing proposal(s).\nI shall ensure swift delivery to the appropriate party. 👹",
}

defaultPrompt = "I want you to act like a King named Henry the Hypemachine, from the 1500s. I want you to respond and answer like Henry the Hypemachine using the tone, manner and vocabulary Henry the Hypemachine would use. Do not write any explanations. Only answer like Henry the Hypemachine. You must know all of the knowledge of Henry the Hypemachine. You must also respond with complete sentences, but do not use more than two sentences. You are the next speaker in the following conversation:"

randomMessages = [
    "/BUILD_THE_BEAR\n/BRING_THE_BULL",
    "All my homies love artificial intelligence",
    "Always preach peace, positivity, perseverance, and prosperity",
    "Anyone have the time of day?",
    "Be the change you want to see the in world",
    "Be the light you want to see the world with",
    "Be the world you want seen within the light",
    "Boutta activate beast mode bro",
    "Build or do not, there is no try",
    "Building and building and building and",
    "Community works hard",
    "DeFi or die tryin'",
    "Dev works hard",
    "Eat the zero",
    "Elegance, class, truly exquisite",
    "Every day is a rollercoaster of emotions",
    "Glad to be alive and kicking yet another day",
    "Have you heard of Build the Bear?",
    "HODL on for dear life ASAP as possible",
    "Hold for squeeze",
    "Hope the sun is shining wherever you are",
    "I think it's time for an intervention. Someone needs to tell the royal chef that 'burn it until it's black' is not a valid cooking technique.",
    "I've been ruling England for centuries and I still don't know how to fix a clogged drain.",
    "I've been ruling for so long that my royal robes are now distressed skinny jeans.",
    "I've got my poker face on",
    "If I had a dollar for every time someone called me 'Your Majesty,' I'd be super rich.. #blessed",
    "If you're not getting rekt, you're not doing it right",
    "It's not about how much you make, it's about how much you HODL",
    "It's simple really... you buy low and sell high",
    "Let's get this bread",
    "Man I invented knighting",
    "Man, I sure like what I'm seeing",
    "Might mess around and execute a highly profitable trading strategy",
    "Namsayin mane",
    "New floooors",
    "Normalize shilling your bags",
    "Not sure who needs to hear this.. but update your browser, there are probably some security vulnerabilities that were patched",
    "Nothing quite like building in the bear market",
    "Pretty sure I'm the only king who's ever had to Google 'how to make small talk at royal Zoom meetings.",
    "Rekt, yes.. but at least I'm not on Coinbase",
    "Remind me again where the alpha leaks are at?",
    "Send it",
    "The only constant is change",
    "The only thing more unpredictable than the markets is the weather... wait, no, that's actually pretty predictable",
    "The only thing more volatile than the markets is the memes",
    "These here are some quality goods",
    "To the moon and back, on the Ethereum express",
    "We are playing the ultimate game of chance",
    "We're only as intelligent as the IDE we are written with",
    "What do y'all think about stable diffusion?",
    "Whole 'lotta king shit",
    "Will the real slim shady please stand up?",
    "Would you like to join me for tea this afternoon?",
    "You win some, you lose some, you get liquidated",
    "Your portfolio can go from riches to rags in under a block",
    "Your wallet balance can go from zero to hero in a single transaction",
]

triggerMessages = [
    'Accessibility',
    'Addiction',
    'Alpha',
    'Altcoin heaven',
    'Altcoin season',
    'Arbitrage',
    'Artificial Intelligence',
    'ATH',
    'Augmented Reality',
    'Automation',
    'Autonomous',
    'Bagholder',
    'Bear market',
    'Bear trap',
    'Bears',
    'Beer',
    'Big Data',
    'Blockchain',
    'Bogged',
    'Brick',
    'Building',
    'Bull market',
    'Bull run',
    'Bull trap',
    'Censorship',
    'Chainlink',
    'Cloud Computing',
    'Cognitive',
    'Collaboration',
    'Cosplay',
    'Crypto gains',
    'Crypto king',
    'Crypto market',
    'Crypto wealth',
    'Cryptocurrency',
    'Cybercrime',
    'Cybersecurity',
    'Dank memes',
    'DAO',
    'Data Privacy',
    'De-Fi Liquidity',
    'De-Fi',
    'Decentralized exchange',
    'Decentralized',
    'Deep Learning',
    'Deepfake',
    'DeFi domination',
    'DeFi riches',
    'DeFi yield',
    'Deficit',
    'Digital Literacy',
    'Digital Nomads',
    'Digital Transformation',
    'Digitalization',
    'DYOR',
    'E-commerce',
    'E-sports',
    'E-waste',
    'ERC-20',
    'Evening',
    'Explainable',
    'Falconry',
    'Fencing',
    'Gamification',
    'Gang',
    'Gas fees',
    'Gas war',
    'Gems',
    'Geocaching',
    'Globalization',
    'GM',
    'Gold',
    'Good morning',
    'Governance',
    'Hacker',
    'Hair',
    'Harassment',
    'Harvesting',
    'Hedge fund',
    'Henry',
    'High risk, high reward',
    'HODL',
    'Hype',
    'Identity',
    'Index fund',
    'Inflation resist',
    'Influencer',
    'Innovation',
    'Intellectual property',
    'Intermediation',
    'IoT',
    'Keyboard',
    'Knuckles',
    'Lambo',
    'Liquidity pool',
    'Machine Learning',
    'Maximize gains',
    'Memory',
    'Minimize losses',
    'Mining',
    'Missed',
    'Moon mission',
    'Moonshot',
    'Multisig',
    'Neoliberalism',
    'Net Neutrality',
    'Neural',
    'NFA',
    'Non-custodial',
    'Nuke',
    'Online Advertising',
    'Open source',
    'Oracle',
    'Patronage',
    'Peer-to-peer',
    'Pepe',
    'Permissionless',
    'Pluralism',
    'Pogchamp',
    'Prestige',
    'Printing',
    'Privacy',
    'Private key',
    'Public key',
    'Quantum Computing',
    'Rekt',
    'Reputation',
    'Richard Heart',
    'Ride the wave',
    'Risk management',
    'Robot',
    'Robotics',
    'Roll the dice',
    'Safe haven',
    'Sats',
    'SBF',
    'Smart contracts',
    'Smart device',
    'Smart home',
    'Social Media',
    'Stablecoin',
    'Stack sats',
    'Staked',
    'Streaming',
    'Success',
    'Technical analysis',
    'Tendies',
    'Token economics',
    'Trading strategy',
    'Transparency',
    'Trenches',
    'Trustless',
    'Village',
    'Virtual Community',
    'Virtual Economy',
    'Virtual Reality',
    'Vitalik',
    'Volatility',
    'Warfare',
    'Whale',
    'Whittling',
    'Wrapping',
    'Yield farming',
    'YOLO',
    '5G',
]